project_id = "bvqbnhisnwzqshkuucam"

[functions.fetch-ics]
verify_jwt = false

[functions.chat-nomos]
verify_jwt = false

[functions.generate-flashcards]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false

[functions.generate-task-title]
verify_jwt = false
